<div class="prose">

<h1>Part 1: Worldwide Meat Consumption</h1>
<p>
	There has been increasing pressure on farmers to produce meat 
	(beef, pork, lamb, chicken and other types of meat that humans eat),
	which has undesirable effects on the environment.
	According to the Food and Agriculture Organization of the United
	Nations, the annual world meat consumption in 1965 was 24.2 kg per
	capita (per person). This had increased to 41.3 kg per capita in 2015.
</p>

<ol type="a" class="marker:font-bold marker:text-[#7FD87B]">
	
<li class="prose">
	<p>
		A member from the original group of experts determined a model for the meat
		consumption since 1965. They defined what x represents (number of years after
		1965), but forgot to define what the y represents. What does the y represent in
		this context? <b>y=0.342x+24.2</b>
	</p>

		<p class="ml-10">
			I think that, in this context, <b>y</b> represents the meat consumption for the years after 1956. This is because
			we cant have a measure of time (<b>x</b>) but not have something to compare it to. <b>y</b> is measured in kgpc
			(kilograms per capita), I know this because the Food and Agriculture Organization of the United Nations measured their
			findings in kgpc.
		</p>
			<div class="bg-[#7FD87B] rounded-xl p-6">
				<img src="/p1a.png" alt="a graph with an equation of y=0.342x+24.2" class="w-80 ml-32">
			</div>
		<p>
			This is the graph of the final equation, according to this graph, the meat consumption per capita gets higher each year and has been since 1965.
		</p>
</li> <br>

<li class="prose">
	<p>
		Experts used the model from part a to predict meat consumption per capita this year (2023)
		Since x represents the number of years since 1965...2023-1965=58
	</p>
		<p class="text-center">
			y=0.342x+24.2 <br>
			y=0.342(58)+24.2 <br>
			y=44.036 <br>
		</p>
	<p>
		The meat consumption per capita in 2023 would be 44.036kg <br>
		Your task: use the model from part a to predict the meat consumption per capita in 2030
	</p>

		<p class="ml-10">
			I predict that the kgpc in 2030 will be 46.43 kg. I got this number by using the same equation used above:
		</p>
		<p class="ml-10 text-center">
			2030 - 1955 = 65 <br>
			
			y=0.342x+24.2 <br>
			y=0.342(65)+24.2 <br>
			y=46.43 <br>
		</p>
		<div class="bg-[#7FD87B] rounded-xl p-6">
			<img src="/p1b.png" alt="a graph with a point at (65, 46.43)" class="w-80 ml-32">
		</div>
		<p class="ml-10">
			What this equations does is find the intersection between x=65 and the line. Since <b>x</b> is the number of years since 1965 and <b>y</b> is meat consumption in kgpc, this means that the point where they intercept is the meat consumption that year, and you can use this to predict the meat consumption at any time.
		</p>
</li> <br>

<li class="prose">
	<p>
		Discuss whether you think this is a realistic model
	</p>

		<p class="ml-10">
			I  think that the model is <i>fairly</i> realistic, to a point. It <i>can</i> be realistic as long as meat consumption has increased at a constant rate since the beginning of time, or at least since 1955. I also think that it's unrealistic that meat consumption would have kept going up when we discovered agriculture, or even recently that large portions of the earth are dedicated to farmland.
		</p>
</li> <br>

<li class="prose">
	<p>
		Do you think this increase in meat consumption is sustainable? <b>Explain</b>
	</p>
	
		<p class="ml-10">
			The rate at which the graph shows meat consumption going up per year, although not realistic, is not sustainable realistically <i>or</i> unrealistically. This is because there is only so much space we can allocate to livestock. And of course we wouldn't be able to survive on meat alone, as plant matter contains nutrients that meat just cant provide. We also could not possibly grow food for the livestock fast enough as to be sustainable. And not to mention the greenhouse has emissions generated by sustaining the amount of livestock required to keep up with the requirements of meat consumption.
		</p>
</li> <br>

<li class="prose">
	<p>
		Determine a linear model for each of developed and developing countries, where x represents the number of years after 1997, and y represents the total meat consumption (in million tonnes)
	</p>

	<table>
		<tr class="bg-[#7FD87B] text-white">
			<th></th>
			<th>1997 meat consumption (million tonnes)</th>
			<th>Average annual increase in meat consumption since 1997 (million tonnes)</th>
		</tr>
		<tr>
			<td>Developed Countries</td>
			<td>98</td>
			<td>0.8</td>
		</tr>
		<tr>
			<td>Developing Countries</td>
			<td>111</td>
			<td>4.6</td>
		</tr>
	</table> 

		<div class="bg-[#7FD87B] rounded-xl ml-10 p-6 flex justify-evenly">
			<div class="flex flex-col">
				<p class="text-center text-white font-bold m-0">Developed Countries</p>
				<img src="/p1cb.png" alt="a graph with a point at (65, 46.43)" class="w-60">
			</div>
			<div class="flex flex-col">
				<p class="text-center text-white font-bold m-0">Developing Countries</p>
				<img src="/p1ca.png" alt="a graph with a point at (65, 46.43)" class="w-60">
			</div>
		</div>
</li> <br>

<li class="prose">
	<p>
		<b>Discuss</b> the degree of accuracy of the models.
	</p>
	
		<p class="ml-10">
			I believe that in a sense of shape, the models are realistic, I think this because more developed countries with sufficient infrastructure in place would have an "advantage" when it comes to meat consumption compared to countries still in the process of developing, indicated by the <b>y-intercept</b>. I also think that they would also have a larger increase in meat consumption (<b>slope</b>) since most developed countries tend to have a larger population, leading to a larger demand for meat thereby increasing meat consumption.
		</p>
</li> <br>

<li class="prose">
	<p>
		<b>Graph</b> each model on the same axes
	</p>
	
		<div class="bg-[#7FD87B] rounded-xl p-6">
			<img src="/p1g.png" alt="a graph with a point at (65, 46.43)" class="h-80 ml-10">
		</div>
</li> <br>

<li class="prose">
	<p>
		What does the slope (gradient) of each line represent? Which slope (gradient) is <u>more concerning</u>? <b>Explain</b>.
	</p>
	
		<p class="ml-10">
			The slope of the lines represents the increase of meat consumption in both developed countries and countries in process of development. The one that belongs to developing countries has a lower slope, this means that the developing country's meat consumption is raising slower, signifying that the countries food supply is smaller or their food production is slower. This all could mean that the country is more prone to starvation or at least lower quality of life.
		</p>
</li> <br>

</ol>
</div>

<style>

	b {
		color: #7FD87B;
	}

	@media (prefers-color-scheme: light) {
		th, td {
			border: 1px solid black;
			padding: 0.5rem;
		}
	}

	@media (prefers-color-scheme: dark) {
		th, td {
			border: 1px solid white;
			padding: 0.5rem;
		}
	}
</style>